### ISSUE TITLE
Does it Plan to open ncnn-int8 source?

### ISSUE THREAD

**Issue by onexuan** [BUG1989/caffe-int8-convert-tools#1]

**Comment by BUG1989** [comment]
yep,it will coming soon.

**Comment by onexuan** [comment]
Great, I will test MobileFaceNet (https://github.com/imistyrain/MobileFaceNet/tree/master/models) by your ncnn-int8,  How does set up parameters to convert these (det1, det2, det3 and MobileFaceNet)?

**Comment by BUG1989** [comment]
hi~
the ncnn-int8 has opened source.I have pulled the request to the ncnn community:
https://github.com/Tencent/ncnn/pull/487
or you can clone the project in my rep https://github.com/BUG1989/ncnn
