### ISSUE TITLE
dequantize and quantize fusion of coadjacent convolution blocks

### ISSUE THREAD

**Issue by nihui** [BUG1989/caffe-int8-convert-tools#11]
fuse dequantize and quantize across convolution blocks via requantize operation
since all int8 scales for activations are all positive, we can place relu activation after the requantize

```
requantize1(X) = quantize2(dequantize1(X) + bias1))
```

less memory footprint, faster quantized activation and less quantization overhead results better performance ;)

senario, current scheme, expected scheme
```
conv1 + relu1 + conv2
```
```
quantize1
int8conv1
dequantize1(+bias)
relu1
quantize2
int8conv2
dequantize2(+bias)
```
```
quantize1
int8conv1
requantize1(+bias+quantize2)
int8relu1
int8conv2
dequantize2(+bias)
```

```
conv1 + relu1 + dwconv2 + relu2 + conv3
```
```
quantize1
int8conv1
dequantize1(+bias)
relu1
quantize2(dw)
int8conv2(dw)
dequantize2(dw+bias)
relu2
quantize3
int8conv3
dequantize3(+bias)
```
```
quantize1
int8conv1
requantize1(+bias+quantize2(dw))
int8relu1
int8conv2(dw)
requantize2(dw+bias+quantize3)
int8relu2
int8conv3
dequantize3(+bias)
```

**Comment by BUG1989** [comment]
The work is done
[merge de/requantize op, optimize some int8 conv layer on arm64-v8a](https://github.com/Tencent/ncnn/pull/867)
