### ISSUE TITLE
caffe-int8-convert-tools  -----Error

### ISSUE THREAD

**Issue by xiangdeyizhang** [BUG1989/caffe-int8-convert-tools#14]
Hi BUG1989，
  when I use caffe-int8-convert-tool-dev.py ,there is an error
File "caffe-int8-convert-tool-dev.py", line 379, in weight_quantize
    raise ValueError("First layer should be input")
ValueError: First layer should be input?

my protxt file has “input”：

input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 300
  dim: 300
}
layer {
  name: "Conv"
  type: "Convolution"
  bottom: "data"
  top: "Conv"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }

**Comment by xiangdeyizhang** [comment]
I have solve it

**Comment by suikammd** [comment]
Hey, how do you sovle this? There is no such layer in deploy.prototxt.

**Comment by Teragump** [comment]
> Hey, how do you sovle this? There is no such layer in deploy.prototxt.

Just upgrade your prototxt file with the tool offered by Caffe:)
