### ISSUE TITLE
Doubts about Mean and Norm parameters

### ISSUE THREAD

**Issue by ricardotapiador** [BUG1989/caffe-int8-convert-tools#15]
Hello,
Your tool is quite interesting. However i dont understand the parameters of Mean and Norm.
Is Mean the average of weights ?

Kind regards

**Comment by BUG1989** [comment]
@ricardotapiador mean or norm value, is based on your training dataset.
mean is the average of training dataset;
norm is the scale of training dataset,sometimes do not use is,default value is 1.0.

**Comment by WIll-Xu35** [comment]
@BUG1989 Hi, I'm still confused about mean and norm.

About mean, what order should I use, BGR or RGB.

About norm, I still can't understand what does it mean? Is it the average norm of each channel? Say if I have a dataset of images, how can I determine the value of norm?

Thanks

**Comment by BUG1989** [comment]
@WIll-Xu35 
example,in the mobilenet_v1.prototxt file
```
name: "MOBILENET"
#  transform_param {
#    scale: 0.017
#    mirror: false
#    crop_size: 224
#    mean_value: [103.94,116.78,123.68]
#  }
```
mean :  the order of mean is depend on you train model
norm : the mean is scale value,default is 1

**Comment by WIll-Xu35** [comment]
@BUG1989 

I couldn't find this transform_param in my prototxt file.

Can I understand it in this way, mean and norm are the preprocessing parameters we use to preprocess our image data input.

For example, when i train the model, each raw input pixel is firstly minus 127.5, multiplied by 0.0078125, and then feed into the model and used to do the training. So the mean should be [127.5, 127.5, 127.5], the norm should be 0.0078125. Is this understanding correct?

Thank you.

**Comment by BUG1989** [comment]
@WIll-Xu35 
Yes, that's right,maybe my expression confused you : )

**Comment by WIll-Xu35** [comment]
@BUG1989 
Thank you for your quick reply and your awesome codes:)
