### ISSUE TITLE
关于此工具量化与TensorRT量化

### ISSUE THREAD

**Issue by JSnobody** [BUG1989/caffe-int8-convert-tools#18]
你好，有个问题想请教一下，也不知道你的联系方式，那就在这里提问好了。
我理解的TensorRT int8量化核心是KL散度校验，那么是不是实现了这些，就相当于实现了TensorRT int8量化呢？你开发的此工具，是不是相当于TensorRT int8量化呢？有什么改进或者不同吗？谢谢

**Comment by BUG1989** [comment]
量化原理上参考的TensorRT int8的PPT，具体实现过程不一定一样，所以生成的table表会存在差异
