### ISSUE TITLE
自己使用此工具对Squeezenet模型进行int8转换遇到问题

### ISSUE THREAD

**Issue by JSnobody** [BUG1989/caffe-int8-convert-tools#20]
你好！
作者给了squeezenet的table，我自己也实际用squeezenet模型转换生成table，但是，我这边产生的table有些地方是：
fire2/squeeze1x1 inf
fire2/expand1x1 inf
fire2/expand3x3 inf
fire3/squeeze1x1 inf
fire3/expand1x1 inf
fire3/expand3x3 inf
fire4/squeeze1x1 inf
fire4/expand1x1 inf
fire4/expand3x3 inf
fire5/squeeze1x1 inf
fire5/expand1x1 inf
......

看着不太对啊！

生成的log好多0，类似的：
conv1: value range 0 - 0.0, interval 0.0, interval num 2048
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

我用作者给的table和我自己转换生成的table分别用ncnn进行推理。
发现作者提供的，推理结果是可以的，而我这边的，结果就不能看了，很差。
所以，我想问，我的做法是不是有问题，不知道哪里出错了，能否指点一下？
谢谢！

**Comment by JSnobody** [comment]
对啦， --mean和--norm，该如何设置

**Comment by BUG1989** [comment]
mean和norm分别对应caffe模型的预处理均值和scale值，images使用训练集或验证集的图片均可

**Comment by JSnobody** [comment]
这个工具对训练集或验证集的图片一般需要多少数量的，我下载了ILSVRC2012，12G，感觉比较多。
我用6万多张图片作为工具测试images，够用不

**Comment by JSnobody** [comment]
关于mean和norm的值。
例子里面给的是mobilenet_v1，--mean 103.94 116.78 123.68 --norm=0.017
应该来自mobilenet_deploy.prototxt：
#  transform_param {
#    scale: 0.017
#    mirror: false
#    crop_size: 224
#    mean_value: [103.94,116.78,123.68]
#  }

但是，squeezenet我并没有找到，怎么办？

**Comment by JSnobody** [comment]
是这个train_val.prototxt吗？
  transform_param {
    crop_size: 227
    mean_value: 104
    mean_value: 117
    mean_value: 123

**Comment by BUG1989** [comment]
@JSnobody 对，就是这个

**Comment by JSnobody** [comment]
好的，scale有的模型没有，我看你的默认值是1.0就可以运行了，是吧。另外有个小问题哈。

MobileNet_v1 SSD | 70.49 | 60.38 | -10.11
这个diff到了10%，你觉得可能导致的原因是？有没有改进的考虑？打算如何解决？
谢谢！

**Comment by BUG1989** [comment]
正在改进，希望能控制在3%以内

**Comment by JSnobody** [comment]
嗯嗯，请问，改进的代码还会更新到github上嘛，我想跟着学习学习

**Comment by BUG1989** [comment]
希望能吧……没什么时间做呀……摊手.jpg

**Comment by JSnobody** [comment]
额，现在就你一个人在做？

**Comment by BUG1989** [comment]
Hobby job : )

**Comment by JSnobody** [comment]
我看ncnn上有conv量化，是在推理的时候遇到conv先量化、再卷积、再反量化吗？只考虑conv，其它layer不用做，是吧？后面会实现其它layer的量化吗？

**Comment by BUG1989** [comment]
从耗时占比而已，conv的耗时最多，所以目前只针对conv进行量化，如果网络结构允许的话，可以支持relu、concat、eltwise、max pooling量化。你可以参考下这里的实验代码[ncnn int8 fuse test](https://github.com/BUG1989/ncnn/tree/ncnn-int8-dev)

**Comment by JSnobody** [comment]
是的，conv耗时最多，对conv做int8量化是有意义的。另外，我还有个问题。
该量化工具是用caffe inference，是否考虑用ncnn inference呢？是否会有影响。
我理解，可能问题不大。但是，如果是用caffe，那么使用者都要去使用caffe，tensorflow模型咋办？
是需要tensorflow->onnx->caffe，关于这个工具的形态是否有新的考虑？
谢谢

**Comment by Teragump** [comment]
@JSnobody 请问最上面的那个问题，你解决了吗？与mean和norm这两个参数有关系吗
