### ISSUE TITLE
pc测试，int8速度降低一半

### ISSUE THREAD

**Issue by lvpiche** [BUG1989/caffe-int8-convert-tools#22]
为什么我用你的工具转出table后：
python caffe-int8-convert-tool-dev.py --proto=model/mobilenet_ssd.prototxt --model=model/mobilenet_ssd.caffemodel --mean 127.5 127.5 127.5 --norm=0.007843 --images=images --output=model/mnet_ssd.table --gpu=1
然后使用./caffe2ncnn mobilenet_ssd.prototxt mobilenet_ssd.caffemodel mobilenet_ssd_300_int8.param mobilenet_ssd_300_int8.bin 256 mnet_ssd.table生成param和bin文件
最后使用生成的param和bin文件替换原来的文件，在pc上测试，速度从80+ms上升到130+ms？
请问下这正常吗？谢谢回答。

**Comment by BUG1989** [comment]
PC上并没有做int8的加速，只是为了验证逻辑而已

**Comment by lvpiche** [comment]
这点我清楚，但是在pc上验证，速度没提升，至少不会慢吧。不知道我的理解对不对。另外--images对于图片的数量等规格有什么特别的要求吗？我发现不一样的数据，产生的table表也有差异。期待你的回答，谢谢。

**Comment by BUG1989** [comment]
1. int8多了quantize/dequantize的操作，编译器自动优化是玄学；
2. --images建议使用训练集或者验证集的数据，大约1k-5k张就可以了。

**Comment by lvpiche** [comment]
好的，谢谢！
