### ISSUE TITLE
网络压缩

### ISSUE THREAD

**Issue by shenghsiaowong** [BUG1989/caffe-int8-convert-tools#24]
您好，你在压缩模型为什么要用到一张训练集的图片，以及测试用的prototxt？

**Comment by BUG1989** [comment]
量化方案是参考的TensorRT的int8实现原理；
images=训练集的一些图片，大约1k-5k就可以了；
只做inference，统计出指定层(conv/convdw)的输入blob数据的最佳截断值。

**Comment by shenghsiaowong** [comment]
$ python caffe-int8-convert-tool.py --help usage: caffe-int8-convert-tool.py [-h] [--proto PROTO] [--model MODEL] [--mean MEAN MEAN MEAN] [--norm NORM] [--images IMAGES] [--output OUTPUT] [--gpu GPU] find the pretrained caffe models int8 quantize scale value optional arguments: -h, --help show this help message and exit --proto PROTO path to deploy prototxt. --model MODEL path to pretrained weights --mean MEAN value of mean --norm NORM value of normalize --images IMAGES path to calibration images --output OUTPUT path to output calibration table file --gpu GPU use gpu to forward 
**$ **_python caffe-int8-convert-tool.py --proto=squeezenet_v1.1.prototxt --model=squeezenet.caffemodel --mean 104 117 123 --images=ILSVRC2012_1k --output=squeezenet_v1.1.table --gpu=1
这里面的均值文件也不是很懂？

**Comment by BUG1989** [comment]
这是mobilenet v1的prototxt中开始的部分，就是这里的mean_value和scale值，有些模型没有scale，就默认1.0
```
name: "MOBILENET"
#  transform_param {
#    scale: 0.017
#    mirror: false
#    crop_size: 224
#    mean_value: [103.94,116.78,123.68]
#  }
layer {
    name: "data"
    type: "Input"
    top: "data"
	input_param {
		shape {dim: 1 dim: 3 dim: 224 dim: 224}
	}
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  convolution_param {
    num_output: 32
    bias_term: false
    pad: 1
    kernel_size: 3
    stride: 2
    weight_filler {
      type: "msra"
    }
  }
}
```
