### ISSUE TITLE
KL计算时疑问

### ISSUE THREAD

**Issue by zw1992** [BUG1989/caffe-int8-convert-tools#26]
您好，请教一个问题，计算KL散度时，把第一个bin去掉了，为什么？认为这部分值太小，忽略吗？

**Comment by BUG1989** [comment]
对称量化，bin[0]是统计的value = 0的数据

1. 0值乘以任意scale还是等于0；
2. 0值我认为没有包含什么信息量；
3. 实验结果，因为存在relu，0值的个数会非常多，KL统计包括0值的话，threshold value就很小，实际量化效果不好，精度掉很多。

**Comment by zw1992** [comment]
``hist, hist_edge = np.histogram(blob_data, bins=INTERVAL_NUM, range=(0, th)) 按代码bin[0]统计的应该是[0,interval]吧，还是说实验中实际是统计的基本是0的值吗?
