### ISSUE TITLE
Not work in convolution layer.

### ISSUE THREAD

**Issue by Alan-Turing-Ko** [BUG1989/caffe-int8-convert-tools#3]
Good convert tool!!
I tried to convert my model and I have some issues.

**conv2a_param_0 161.69534342797343
conv2_param_0 273.37462513263256
conv3a_param_0 198.5867022152598
conv3_param_0 533.0213728867503
conv4a_param_0 146.93212834686443
conv4_param_0 406.008502200532
conv5a_param_0 237.84033457170227
conv5_param_0 430.328425008172**
data 184.220261804279
conv1 32.20969187597571
slice1_1 39.3371286651116
eltwise1 76.43406224473419

When passing conv2a on ncnn, I got all NaN values.
************************************************
When I convert model, I got following warnings every time.

caffe-int8-convert-tool.py:113: RuntimeWarning: divide by zero encountered in true_divide
  return np.sum(dist_a[nonzero_inds] * np.log(dist_a[nonzero_inds] / dist_b[nonzero_inds]))
data                 bin : 2019     threshold : 0.689392   interval : 0.000341   scale : 184.220262
caffe-int8-convert-tool.py:187: RuntimeWarning: invalid value encountered in double_scalars
  expand_value = quantize_distribution[i] / count

And with this error, when I inference on ncnn, I got all NaN values.
I use bmp images for image dataset.
and norm is 1/256.

What could be the problem?
Hope to any suggestions.

**Comment by BUG1989** [comment]
The value in the calibration table file is NaN?
If the value in the calibration table is OK,but when you inference on ncnn, you got all NaN values......which repo do you used?

**Comment by Alan-Turing-Ko** [comment]
Thanks for your reply.
No calibration table file is OK.
Tencent/ncnn (dbf1c405d48f644605244137a827526349ef1d0d).
I am running on ARM platform.

**Comment by BUG1989** [comment]
Yes,you can ignore the RuntimeWarnings,and it will be fixed soon.

**Comment by Alan-Turing-Ko** [comment]
So Why I got NaN values?
I've checked latest ncnn repo(9843b9e158905e017047c542d34245b16d45e700) again.
But got same result.
