### ISSUE TITLE
Converted Mobilefacenet_Res model, low accuracy

### ISSUE THREAD

**Issue by WIll-Xu35** [BUG1989/caffe-int8-convert-tools#36]
Original issue was at [https://github.com/Tencent/ncnn/issues/798].

I've got a mobilefacenet model (with some extra res blocks), and converted it to ncnn using caffe2ncnn, and the performance is almost the same as running on caffe.

However, after I use the caffe int8 quantize tool, transfer it to ncnn int8 quantized model, there is a massive performance drop. I first suspect the preprocessing of the image (since I'm new to c++), but after I use the same inference code for int8 model on fp model, the fp model's performance is good, so the preprocess should be fine. The problem should be the quantized int8 ncnn model. Maybe I did something wrong during the quantization table creation? Or during the quantized ncnn transformation?

Would you please help me solve this issue, I'm now focusing to get the quantized model working on ncnn.

Many thanks.

**Comment by BUG1989** [comment]
Maybe disable quantize the first layer and the last layer, it can reduce the performance drop.
Two Steps:

1. [mixed-precision-inference](https://github.com/Tencent/ncnn/wiki/quantized-int8-inference#)
2. [the-runtime-way-no-model-binary-reduction](https://github.com/Tencent/ncnn/wiki/quantized-int8-inference#the-runtime-way-no-model-binary-reduction)

**Comment by WIll-Xu35** [comment]
Ok, I'll have a try.

Will it matter if I only provide around 200 images as calibration set? (But it shouldn't since my calibration set is my test set, which means my accuracy is calculated on this calibration set, whose loss has been minimized)

**Comment by WIll-Xu35** [comment]
@BUG1989 

I've followed your instructions. Deleted the first layer and the last layer in the table file, then create ncnn model with parameter 0 (runtime way), and then run inference as usual. The result is much better, accuracy dropped from 99.40% to 99.33%.

But I'm confused about two things. First thing is that how does runtime way differ from the offline way? Does it store the original weights and quantize the weight during model loading? While the offline way quantizes all the weights and stores them in int8 form?

The other thing is that the original float point model generate embedding, whose value is usually around 1. But while using offline model (which has a really bad performance), the generated embedding's value is so big, usually billions. And if I use the runtime way (deleted the first and last layer param in table file), the generated embeddings are like the ones from the original float point model (usually around 1). I'm not sure while using the offline way, whether the intermediate layers are still using int8 computation or all of the model just back to floating point calculation?

Thanks.

**Comment by BUG1989** [comment]
Test your guess in the simplest way is running your model in a armv7a device.If the the intermediate layers are still using int8 computation,the speed maybe faster than original fp32 model.
I think you're doing it the right way that using the caffe2ncnn tool.


`caffe2ncnn mobilefacenet.prototxt mobilefacenet.caffemodel mobilefacenet-int8.param mobilefacenet-int8.bin 0 mobilefacenet.table`

**Comment by BUG1989** [comment]
@WIll-Xu35 
BTW,How big is your test dataset.

**Comment by WIll-Xu35** [comment]
Thanks for your instant reply.

I'll test it on hardware later. So currently if I encounter a massive performance drop, using floating point calculation on the first and last layer is the best workaround, right?

I'll let you know my test results on hardware once I've done it. Thank you so much for your help and looking forward to a fully quantized version with minor performance drop:)

**Comment by WIll-Xu35** [comment]
My testset is pretty small, 230 aligned face images. I also use this testset as the calibration dataset to generate the table file.

**Comment by WIll-Xu35** [comment]
I did a little search, armv7a is limited to a small set of chips?

My hardware is rk3399, which has dual cortex a72 and quad cortex a53. Both of them seems to works on armv8a. I've seen your PR on ncnn repo, that says will support armv8a very soon. So I'll be able to use the quantized model on my rk3399 developer kit later, right?

**Comment by BUG1989** [comment]
@WIll-Xu35 

[Brief History of Lower Precision in Deep Learning](https://software.intel.com/en-us/articles/lower-numerical-precision-deep-learning-inference-and-training)

> Thanks for your instant reply.
> 
> I'll test it on hardware later. So currently if I encounter a massive performance drop, using floating point calculation on the first and last layer is the best workaround, right?
> 
> I'll let you know my test results on hardware once I've done it. Thank you so much for your help and looking forward to a fully quantized version with minor performance drop:)

**Comment by BUG1989** [comment]
@WIll-Xu35 


> I did a little search, armv7a is limited to a small set of chips?
> 
> My hardware is rk3399, which has dual cortex a72 and quad cortex a53. Both of them seems to works on armv8a. I've seen your PR on ncnn repo, that says will support armv8a very soon. So I'll be able to use the quantized model on my rk3399 developer kit later, right?

OK,You can try it later on your developer kit

**Comment by WIll-Xu35** [comment]
@BUG1989 Much appreciated!

**Comment by WIll-Xu35** [comment]
@BUG1989 Using the quantized model single threaded on a single cortex A72, inference time dropped from 260ms to 200ms. So the model seems to be running on quantized mode.

Although the quantization shortens the inference time a bit, it still takes too long to inference. Any idea how to further improve the inference speed without degrading the accuracy too badly?

I was reading about pruning and maybe it can be a good starting point? I've seem there was a sparse-connection.py file in this repo that seems to do the pruning and I was planning to try it. But it is gone now, why is that?

Anyway, thank you so much for your help:)

**Comment by andeyeluguo** [comment]
@WIll-Xu35 how did you get the accuracy ？Can you give the corresponding quantization layer in caffe? thanks.

**Comment by WIll-Xu35** [comment]
@andeyeluguo The model I used is for facial recognition, simply quantize the model and do inference on my private dataset and get the accuracy.

The model is mobilefacenet model with some extra res blocks. I first tried to quantize all the layers and the result is not acceptable. Then following the author's instructions, I quantize all the layers except the first conv layer and the last fc layer, and the result looks good.

**Comment by andeyeluguo** [comment]
@WIll-Xu35   Did you get the result of test on caffe?

**Comment by andeyeluguo** [comment]
I guess you write a quantilization layer of caffe, then test ?

**Comment by WIll-Xu35** [comment]
@andeyeluguo I did NOT use caffe to do quantized inference. I use this tool to generate table file for quantization, then feed the table file to ncnn for generating ncnn quantized model. Finally test the result using ncnn and calculate accuracy.
