### ISSUE TITLE
convolution_param stride default value

### ISSUE THREAD

**Issue by TSuanHM** [BUG1989/caffe-int8-convert-tools#38]
if(layer.type == "Convolution" and layer.convolution_param.kernel_size[0] == 3 and  layer.convolution_param.stride[0] == 1):

 if(layer.type == "Convolution" and layer.convolution_param.kernel_size[0] == 3 and (len(layer.convolution_param.stride)==0 or layer.convolution_param.stride[0] == 1)):

**Comment by BUG1989** [comment]
Wow, thanks a lot!
www~

**Comment by BUG1989** [comment]
https://github.com/BUG1989/caffe-int8-convert-tools/commit/b2938e0b35b15af9f908720db27ea7f86d8970e8
