### ISSUE TITLE
Does the version of protobuf affect the results?

### ISSUE THREAD

**Issue by BladeRunner2050** [BUG1989/caffe-int8-convert-tools#39]
Hi, I try the new release of Apr 3, 2019, but it end up with “IndexError: list index (0) out of range” when calling "layer.convolution_param.kernel_size[0]", so I think it may be because the version of protobuf, which is 3.6.1 in my case, and what is yours?

**Comment by BUG1989** [comment]
@BladeRunner2050 
https://github.com/BUG1989/caffe-int8-convert-tools/issues/38#issue-431328563

**Comment by BUG1989** [comment]
https://github.com/BUG1989/caffe-int8-convert-tools/commit/b2938e0b35b15af9f908720db27ea7f86d8970e8
