### ISSUE TITLE
per-group input and weight int8_scale for group convolution

### ISSUE THREAD

**Issue by nihui** [BUG1989/caffe-int8-convert-tools#4]
scenario 1
```
A channel = 10
B channel = 10
A -> depthwiseconv -> B
```
expected behavior
generate 10 int8_scale for A, one for each channel
generate 10 int8_scale for depthwiseconv weight, one for each channel

scenario 2
```
A channel = 10
B channel = 10
A -> conv (group=2) -> B
```
expected behavior
generate 2 int8_scale for A, one for each 5 channels
generate 2 int8_scale for conv weight, one for each group

**Comment by BUG1989** [comment]
Support this feature by caffe-int8-convert-tool-dev.py.It may take a long time to implement.I will try to optimize it
