### ISSUE TITLE
QUANTIZE_WINOGRAND_NUM 的作用

### ISSUE THREAD

**Issue by sxsxsx** [BUG1989/caffe-int8-convert-tools#41]
请问QUANTIZE_WINOGRAND_NUM这个值有什么作用啊？为什么要设置为31？望告知 谢谢~

**Comment by BUG1989** [comment]
@sxsxsx 为了配合ncnn推理框架中conv3x3s1 int8 winograd F(4,3)的实现，防止kernel进行winograd 转换数据溢出。
