### ISSUE TITLE
报个case：量化后某个层的weight scale全为0

### ISSUE THREAD

**Issue by z13974509906** [BUG1989/caffe-int8-convert-tools#42]
如题
![image](https://user-images.githubusercontent.com/20511825/57687847-c54abb00-766e-11e9-909a-b833e426ae07.png)

如果用这样的table去给ncnn做量化的话，该层的输出就只剩下bias了（0 * weight ＋bias）。
这算是bug吗？

**Comment by BUG1989** [comment]
@z13974509906 尝试把这段判断逻辑屏蔽了试试看？
https://github.com/BUG1989/caffe-int8-convert-tools/blob/80e807c097e718e2b98d3a2b4a7f083b26ad8083/caffe-int8-convert-tool-dev-weight.py#L99
