### ISSUE TITLE
TypeError: unorderable types: int() > str()

### ISSUE THREAD

**Issue by 1343464520** [BUG1989/caffe-int8-convert-tools#45]
Hi, How to fix this error? Thank you!
![typeError](https://user-images.githubusercontent.com/24668916/57913864-169db900-78c0-11e9-85a6-bf66a6b84b49.png)

**Comment by 1343464520** [comment]
@BUG1989

**Comment by AnsonHooL** [comment]
I met the same error as well.@BUG1989
you can use this tool. [https://github.com/lyk125/caffe-int8-convert-tools], it can work.@1343464520

**Comment by imistyrain** [comment]
You should use python 2.7 instead of python 3.*
