### ISSUE TITLE
支持yolo量化吗？

### ISSUE THREAD

**Issue by shuxiao9058** [BUG1989/caffe-int8-convert-tools#47]
如题

**Comment by infrontofme** [comment]
请教一下，支持吗？另外您知道生成的table文件里各参数的含义吗？

**Comment by BUG1989** [comment]
如果您是想使用 ncnn 部署请参考 https://github.com/Tencent/ncnn/tree/master/tools/quantize
参数含义如下：

- conv0_param0  0.5，conv0 卷积的 weight 权重的量化 scale，即 int8 = round( fp32 * scale).clamp( -127, 127 )，分通道量化的话，就有 output_channel_num 个 scale value

- conv0 0.8，conv0 卷积的 输入数据的量化 scale，即 int8 = round( fp32 * scale).clamp( -127, 127 )，目前这个只支持不分通道的量化，即每一层只有一个输入量化 scale
