### ISSUE TITLE
得到table文件后，想转成int8的caffemodel文件

### ISSUE THREAD

**Issue by shonehang** [BUG1989/caffe-int8-convert-tools#51]
现在已经得到了table文件
想转成int8的caffemodel文件应该怎么入手呢？
谢谢~

**Comment by BUG1989** [comment]
这个工程，主要是服务于ncnn推理框架的

**Comment by Dongz666** [comment]
同问，ncnn model 和caffe model之间有转换关系吗？在asic芯片上跑，似乎用不了ncnn

**Comment by Dongz666** [comment]
这个作者能提供一下实现的思路吗，使用ncnn model的table文件解析出各层的参数可以吗？我关注到https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure

**Comment by infrontofme** [comment]
@zhiwei-dong 请问你是如何解决的呢？

**Comment by BUG1989** [comment]
请问 @infrontofme  @zhiwei-dong  泥萌为什么要转换成 int8 的 caffemodel 呢？

**Comment by zhiwei-dong** [comment]
我这边似乎解决问题了，之前刚接触思路很奇怪。

**Comment by KellyZhqy** [comment]
> 我这边似乎解决问题了，之前刚接触思路很奇怪。

请问你是怎么解决的呢？方便交流一下吗？

**Comment by zhiwei-dong** [comment]
加微信说吧，DONGZHIWEI8021

On Oct 21, 2020, at 2:45 PM, KellyZhqy <notifications@github.com<mailto:notifications@github.com>> wrote:



我这边似乎解决问题了，之前刚接触思路很奇怪。

请问你是怎么解决的呢？方便交流一下吗？

**Comment by zhiwei-dong** [comment]
> > 我这边似乎解决问题了，之前刚接触思路很奇怪。
> 
> 请问你是怎么解决的呢？方便交流一下吗？

哥们加个微信说吧，DONGZHIWEI8021

**Comment by BUG1989** [comment]
@zhiwei-dong 我也可以来旁听下吗？

**Comment by BUG1989** [comment]
@zhiwei-dong 好像加不了……我的是 qtang_321

**Comment by zhiwei-dong** [comment]
@BUG1989 😂我只是想问问他想搞什么，看看是不是也是方向错了，求大佬放过，我来加下您。
