### ISSUE TITLE
请问这个不能量化mobilenetyolov3吗

### ISSUE THREAD

**Issue by MaxwellAlen** [BUG1989/caffe-int8-convert-tools#53]
我试着量化mobilenetyolov3但是没有成功

**Comment by BUG1989** [comment]
@MaxwellAlen 能贴一下报错的信心吗

**Comment by MaxwellAlen** [comment]
@

liu@EAIU:~/caffe-int8-convert-tools$ python3 caffe-int8-convert-tool-dev-weight.py --proto=test/models/mobilenet_yolov3_lite_bn_deploy.prototxt --model=test/models/mobilenet_yolov3_lite_deploy_iter_3000.caffemodel --mean 1.0 1.0 1.0 --norm=0.017 --images=test/images/  --group=1 --gpu=1
Namespace(gpu=1, group=1, images='test/images/', mean=[1.0, 1.0, 1.0], model='test/models/mobilenet_yolov3_lite_deploy_iter_3000.caffemodel', norm=[0.017], output='calibration-dev.table', proto='test/models/mobilenet_yolov3_lite_bn_deploy.prototxt')
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0710 08:37:52.969758  7312 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0710 08:37:52.969781  7312 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0710 08:37:52.969784  7312 _caffe.cpp:125] Net('test/models/mobilenet_yolov3_lite_bn_deploy.prototxt', 1, weights='test/models/mobilenet_yolov3_lite_deploy_iter_3000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 2321:33: Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".
F0710 08:37:52.984974  7312 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: test/models/mobilenet_yolov3_lite_bn_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by BUG1989** [comment]
@MaxwellAlen 看来是你本机的caffe并不支持“yolov3_detection_output_param"这个参数呀

**Comment by MaxwellAlen** [comment]
> @MaxwellAlen 看来是你本机的caffe并不支持“yolov3_detection_output_param"这个参数呀

请问这个是怎么导致的呢?

**Comment by MaxwellAlen** [comment]
> @MaxwellAlen 看来是你本机的caffe并不支持“yolov3_detection_output_param"这个参数呀

谢谢你 BUG1989  我知道了 是我多个版本caffe 我的环境变量没有更新。 感谢 @

**Comment by mitliucak** [comment]
> > @MaxwellAlen 看来是你本机的caffe并不支持“yolov3_detection_output_param"这个参数呀
> 
> 谢谢你 BUG1989 我知道了 是我多个版本caffe 我的环境变量没有更新。 感谢 @

修改caffe的环境变量 就可以解决这个bug吗 我在bashrc里面修改了 但是bug还是存在
