### ISSUE TITLE
pytorch 版本报错  'dict' object has no attribute 'named_modules'

### ISSUE THREAD

**Issue by Enshall** [BUG1989/caffe-int8-convert-tools#58]
你好 @BUG1989 and 大家
我在尝试pytorch版本时 weight_quantize(net)函数出现如题错误:
    for name, layer in net.named_modules():
AttributeError: 'dict' object has no attribute 'named_modules'
提前感谢可能的帮助!!
谢谢!

**Comment by BUG1989** [comment]
@Enshall PyTorch的版本不能正常工作，已经删掉了，如果你想在ncnn中使用，可以使用
ncnn/tools/quantize中的工具。使用方法应该是这样的

1. PyTorch model -> onnx model
2. onnx model -> ncnn model
3. using those tools in the path_ncnn/src/tools/quantize
4. ncnn2table
5. ncnn2int8

**Comment by HKLee2040** [comment]
@BUG1989 
I'm still interested in pytorch version.  Could you share pytorch tools to me?
