### ISSUE TITLE
请问作者试过量化语义分割网络模型吗？

### ISSUE THREAD

**Issue by duzeyan** [BUG1989/caffe-int8-convert-tools#61]
感谢作者开源的这个量化工具。我在tensorRT 5.0上量化过分类网络和检测网络，量化后效果损失的都不是很大。但是尝试量化一个2分类的语义分割网络(区分目标前景和背景)，效果就差强人意。不知道作者是否做过这方面的工作，可以分享一下见解。感谢。

**Comment by BUG1989** [comment]
暂时没有做过......
