### ISSUE TITLE
I found the tool not support 1x3 3x1 kernels 

### ISSUE THREAD

**Issue by victorygogogo** [BUG1989/caffe-int8-convert-tools#8]
dear @BUG1989 
 
I found the tool not support 1x3 3x1 kernels

If I want to get the 1x3 3x1 int8 scale ,how can I do ?

**Comment by BUG1989** [comment]
Hi @victorygogogo 
Thank you very much for using this tool.
You can modify the function “weight_quantize” to support the conv1x3/3x1 layers

**Comment by victorygogogo** [comment]
@BUG1989   
thank you!
